#!/usr/bin/env node

const ezs = require('ezs');
ezs.use(require('ezs-basics'));
ezs.use(require('..'));

const output = 'language.raw,doi,id';

process.stdin.resume();
process.stdin.setEncoding('utf8');
process.stdin
  .pipe(ezs('stringify'))
  // .pipe(ezs('concat'))
  .pipe(ezs('ISTEXCorpus'))
  .pipe(ezs('ISTEXQuery', { params: { output } }))
  .pipe(ezs('ISTEXHarvest'))
  .pipe(ezs('ISTEXRequest'))
  .pipe(ezs('ISTEXHits'))
  .pipe(ezs('flatten'))
  .pipe(ezs('triplify', { property: 'http://purl.org/ontology/bibo/doi' }))
  // .pipe(ezs('jsonify'))
  .pipe(process.stdout)
;

